server:
  port: 9009
spring:
  application:
    name: tensquare-sms
  rabbitmq:
    host: 192.168.130.131
aliyun:
  sms:
    accessKeyId: LTAI4FrHnuhtWBJF5q2PUk4f
    accessKeySecret: 8y3SHDWKs7dJY2lIKKh2BnbYjJOUrH
    template_code: SMS_174028585
    sign_name: 肉肉肉商城